apiVersion: v2
name: reana
description: REANA reproducible research data analysis platform
home: www.reana.io
icon: http://www.reana.io/static/img/logo-reana.svg
sources:
  - https://github.com/reanahub/reana
  - https://github.com/reanahub/reana-client
  - https://github.com/reanahub/reana-server
  - https://github.com/reanahub/reana-workflow-controller
  - https://github.com/reanahub/reana-workflow-engine-cwl
  - https://github.com/reanahub/reana-workflow-engine-serial
  - https://github.com/reanahub/reana-workflow-engine-yadage
  - https://github.com/reanahub/reana-workflow-engine-snakemake
  - https://github.com/reanahub/reana-job-controller
  - https://github.com/reanahub/reana-commons
  - https://github.com/reanahub/reana-db
  - https://github.com/reanahub/pytest-reana
  - https://github.com/reanahub/www.reana.io
keywords:
  - research-data
  - reproducible-analyses
  - reproducible-workflows
  - kubernetes
  - containers
  - cwl
  - reusable-science
type: application
# Chart version.
version: 0.9.0-alpha.11
kubeVersion: ">= 1.19.0-0 < 1.26.0-0"
